package protocol

// Request command constants
const (
	CLOSE           = "CLOSE"
	LOGIN           = "LOGIN"
	INTERNAL_LOGIN  = "INTERNAL_LOGIN"
	CHECK_LOGIN     = "CHECK_LOGIN"
	CHECK_SESSION   = "CHECK_SESSION"
	GET_LOGIN_LIST  = "GET_LOGIN_LIST"

	// Object commands
	OBJECT_INFO                       = "OBJECT_INFO"
	OBJECT_THREAD_LIST                = "OBJECT_THREAD_LIST"
	OBJECT_THREAD_DETAIL              = "OBJECT_THREAD_DETAIL"
	OBJECT_THREAD_CONTROL             = "OBJECT_THREAD_CONTROL"
	OBJECT_ENV                        = "OBJECT_ENV"
	OBJECT_CLASS_LIST                 = "OBJECT_CLASS_LIST"
	OBJECT_LOAD_CLASS_BY_STREAM       = "OBJECT_LOAD_CLASS_BY_STREAM"
	OBJECT_CLASS_DESC                 = "OBJECT_CLASS_DESC"
	OBJECT_CHECK_RESOURCE_FILE        = "OBJECT_CHECK_RESOURCE_FILE"
	OBJECT_DOWNLOAD_JAR               = "OBJECT_DOWNLOAD_JAR"
	OBJECT_STAT_LIST                  = "OBJECT_STAT_LIST"
	OBJECT_RESET_CACHE                = "OBJECT_RESET_CACHE"
	OBJECT_SET_KUBE_SEQ               = "OBJECT_SET_KUBE_SEQ"
	OBJECT_ACTIVE_SERVICE_LIST        = "OBJECT_ACTIVE_SERVICE_LIST"
	OBJECT_ACTIVE_SERVICE_LIST_GROUP  = "OBJECT_ACTIVE_SERVICE_LIST_GROUP"
	OBJECT_TODAY_FULL_LIST            = "OBJECT_TODAY_FULL_LIST"
	OBJECT_REMOVE                     = "OBJECT_REMOVE"
	OBJECT_HEAPHISTO                  = "OBJECT_HEAPHISTO"
	OBJECT_THREAD_DUMP                = "OBJECT_THREAD_DUMP"

	// Trigger commands
	TRIGGER_ACTIVE_SERVICE_LIST            = "TRIGGER_ACTIVE_SERVICE_LIST"
	TRIGGER_THREAD_DUMP                    = "TRIGGER_THREAD_DUMP"
	TRIGGER_THREAD_DUMPS_FROM_CONDITIONS   = "TRIGGER_THREAD_DUMPS_FROM_CONDITIONS"
	TRIGGER_THREAD_LIST                    = "TRIGGER_THREAD_LIST"
	TRIGGER_HEAPHISTO                      = "TRIGGER_HEAPHISTO"
	TRIGGER_BLOCK_PROFILE                  = "TRIGGER_BLOCK_PROFILE"
	TRIGGER_MUTEX_PROFILE                  = "TRIGGER_MUTEX_PROFILE"
	TRIGGER_DUMP_REASON                    = "TRIGGER_DUMP_REASON"
	TRIGGER_DUMP_REASON_TYPE_CPU_EXCEEDED  = "TRIGGER_DUMP_REASON_TYPE_CPU_EXCEEDED"

	// Object dump and profile commands
	OBJECT_SYSTEM_GC              = "OBJECT_SYSTEM_GC"
	OBJECT_DUMP_FILE_LIST         = "OBJECT_DUMP_FILE_LIST"
	OBJECT_DUMP_FILE_DETAIL       = "OBJECT_DUMP_FILE_DETAIL"
	OBJECT_CALL_HEAP_DUMP         = "OBJECT_CALL_HEAP_DUMP"
	OBJECT_LIST_HEAP_DUMP         = "OBJECT_LIST_HEAP_DUMP"
	OBJECT_DOWNLOAD_HEAP_DUMP     = "OBJECT_DOWNLOAD_HEAP_DUMP"
	OBJECT_DELETE_HEAP_DUMP       = "OBJECT_DELETE_HEAP_DUMP"
	OBJECT_CALL_CPU_PROFILE       = "OBJECT_CALL_CPU_PROFILE"
	OBJECT_CALL_BLOCK_PROFILE     = "OBJECT_CALL_BLOCK_PROFILE"
	OBJECT_CALL_MUTEX_PROFILE     = "OBJECT_CALL_MUTEX_PROFILE"

	// Object list and socket commands
	OBJECT_LIST_REAL_TIME    = "OBJECT_LIST_REAL_TIME"
	OBJECT_LIST_LOAD_DATE    = "OBJECT_LIST_LOAD_DATE"
	OBJECT_REMOVE_INACTIVE   = "OBJECT_REMOVE_INACTIVE"
	OBJECT_REMOVE_IN_MEMORY  = "OBJECT_REMOVE_IN_MEMORY"
	OBJECT_FILE_SOCKET       = "OBJECT_FILE_SOCKET"
	OBJECT_SOCKET            = "SOCKET"

	// Server commands
	SERVER_VERSION     = "SERVER_VERSION"
	SERVER_LOG_LIST    = "SERVER_LOG_LIST"
	SERVER_LOG_DETAIL  = "SERVER_LOG_DETAIL"

	// Host commands
	HOST_TOP             = "HOST_TOP"
	HOST_PROCESS_DETAIL  = "HOST_PROCESS_DETAIL"
	HOST_DISK_USAGE      = "HOST_DISK_USAGE"
	HOST_NET_STAT        = "HOST_NET_STAT"
	HOST_WHO             = "HOST_WHO"
	HOST_MEMINFO         = "HOST_MEMINFO"

	// KVM commands
	KVM_NET_PERF   = "KVM_NET_PERF"
	KVM_DISK_PERF  = "KVM_DISK_PERF"

	// Server thread and status commands
	SERVER_THREAD_LIST    = "SERVER_THREAD_LIST"
	SERVER_THREAD_DETAIL  = "SERVER_THREAD_DETAIL"
	SERVER_ENV            = "SERVER_ENV"
	SERVER_STATUS         = "SERVER_STATUS"
	SERVER_TIME           = "SERVER_TIME"
	SERVER_DB_LIST        = "SERVER_DB_LIST"
	SERVER_DB_DELETE      = "SERVER_DB_DELETE"
	REMOTE_CONTROL        = "REMOTE_CONTROL"
	REMOTE_CONTROL_ALL    = "REMOTE_CONTROL_ALL"
	CHECK_JOB             = "CHECK_JOB"

	// Transaction and XLog commands
	TRANX_REAL_TIME                = "TRANX_REAL_TIME"
	TRANX_LOAD_TIME                = "TRANX_LOAD_TIME"
	XLOG_READ_BY_TXID              = "XLOG_READ_BY_TXID"
	XLOG_READ_BY_GXID              = "XLOG_READ_BY_GXID"
	XLOG_LOAD_BY_TXIDS             = "XLOG_LOAD_BY_TXIDS"
	XLOG_LOAD_BY_GXID              = "XLOG_LOAD_BY_GXID"
	TRANX_PROFILE                  = "TRANX_PROFILE"
	TRANX_PROFILE_FULL             = "TRANX_PROFILE_FULL"
	TRANX_REAL_TIME_GROUP          = "TRANX_REAL_TIME_GROUP"
	TRANX_REAL_TIME_GROUP_LATEST   = "TRANX_REAL_TIME_GROUP_LATEST"
	TRANX_LOAD_TIME_GROUP          = "TRANX_LOAD_TIME_GROUP"
	TRANX_LOAD_TIME_GROUP_V2       = "TRANX_LOAD_TIME_GROUP_V2"
	QUICKSEARCH_XLOG_LIST          = "QUICKSEARCH_XLOG_LIST"
	SEARCH_XLOG_LIST               = "SEARCH_XLOG_LIST"

	// Counter past time commands
	COUNTER_PAST_TIME           = "COUNTER_PAST_TIME"
	COUNTER_PAST_TIME_ALL       = "COUNTER_PAST_TIME_ALL"
	COUNTER_PAST_TIME_TOT       = "COUNTER_PAST_TIME_TOT"
	COUNTER_PAST_TIME_GROUP     = "COUNTER_PAST_TIME_GROUP"
	COUNTER_PAST_DATE           = "COUNTER_PAST_DATE"
	COUNTER_PAST_DATE_ALL       = "COUNTER_PAST_DATE_ALL"
	COUNTER_PAST_DATE_TOT       = "COUNTER_PAST_DATE_TOT"
	COUNTER_PAST_DATE_GROUP     = "COUNTER_PAST_DATE_GROUP"
	COUNTER_PAST_LONGDATE_GROUP = "COUNTER_PAST_LONGDATE_GROUP"
	COUNTER_PAST_LONGDATE_ALL   = "COUNTER_PAST_LONGDATE_ALL"
	COUNTER_PAST_LONGDATE_TOT   = "COUNTER_PAST_LONGDATE_TOT"

	// Counter real time commands
	COUNTER_REAL_TIME                = "COUNTER_REAL_TIME"
	COUNTER_REAL_TIME_ALL            = "COUNTER_REAL_TIME_ALL"
	COUNTER_REAL_TIME_TOT            = "COUNTER_REAL_TIME_TOT"
	COUNTER_REAL_TIME_OBJECT_ALL     = "COUNTER_REAL_TIME_OBJECT_ALL"
	COUNTER_REAL_TIME_OBJECT_TYPE_ALL = "COUNTER_REAL_TIME_OBJECT_TYPE_ALL"
	COUNTER_REAL_TIME_MULTI          = "COUNTER_REAL_TIME_MULTI"
	COUNTER_REAL_TIME_GROUP          = "COUNTER_REAL_TIME_GROUP"
	COUNTER_REAL_TIME_ALL_MULTI      = "COUNTER_REAL_TIME_ALL_MULTI"

	// Internal counter commands
	INTR_COUNTER_REAL_TIME_BY_OBJ = "INTR_COUNTER_REAL_TIME_BY_OBJ"

	// Counter today commands
	COUNTER_TODAY       = "COUNTER_TODAY"
	COUNTER_TODAY_ALL   = "COUNTER_TODAY_ALL"
	COUNTER_TODAY_TOT   = "COUNTER_TODAY_TOT"
	COUNTER_TODAY_GROUP = "COUNTER_TODAY_GROUP"

	// Active speed and map commands
	ACTIVESPEED_REAL_TIME              = "ACTIVESPEED_REAL_TIME"
	ACTIVESPEED_REAL_TIME_GROUP        = "ACTIVESPEED_REAL_TIME_GROUP"
	ACTIVESPEED_GROUP_REAL_TIME        = "ACTIVESPEED_GROUP_REAL_TIME"
	ACTIVESPEED_GROUP_REAL_TIME_GROUP  = "ACTIVESPEED_GROUP_REAL_TIME_GROUP"
	SHOW_REAL_TIME_STRING              = "SHOW_REAL_TIME_STRING"
	COUNTER_MAP_REAL_TIME              = "COUNTER_MAP_REAL_TIME"

	// Alert commands
	ALERT_REAL_TIME         = "ALERT_REAL_TIME"
	ALERT_LOAD_TIME         = "ALERT_LOAD_TIME"
	ALERT_DAILY_COUNT       = "ALERT_DAILY_COUNT"
	ALERT_TITLE_COUNT       = "ALERT_TITLE_COUNT"
	GET_COUNTER_EXIST_DAYS  = "GET_COUNTER_EXIST_DAYS"

	// Text commands
	GET_TEXT          = "GET_TEXT"
	GET_TEXT_100      = "GET_TEXT_100"
	GET_TEXT_PACK     = "GET_TEXT_PACK"
	GET_TEXT_ANY_TYPE = "GET_TEXT_ANY_TYPE"

	// Key-Value store commands
	GET_GLOBAL_KV      = "GET_GLOBAL_KV"
	SET_GLOBAL_KV      = "SET_GLOBAL_KV"
	SET_GLOBAL_TTL     = "SET_GLOBAL_TTL"
	GET_CUSTOM_KV      = "GET_CUSTOM_KV"
	SET_CUSTOM_KV      = "SET_CUSTOM_KV"
	SET_CUSTOM_TTL     = "SET_CUSTOM_TTL"
	GET_GLOBAL_KV_BULK = "GET_GLOBAL_KV_BULK"
	SET_GLOBAL_KV_BULK = "SET_GLOBAL_KV_BULK"
	GET_CUSTOM_KV_BULK = "GET_CUSTOM_KV_BULK"
	SET_CUSTOM_KV_BULK = "SET_CUSTOM_KV_BULK"

	// Configuration commands
	GET_CONFIGURE_SERVER          = "GET_CONFIGURE_SERVER"
	SET_CONFIGURE_SERVER          = "SET_CONFIGURE_SERVER"
	LIST_CONFIGURE_SERVER         = "LIST_CONFIGURE_SERVER"
	GET_CONFIGURE_WAS             = "GET_CONFIGURE_WAS"
	SET_CONFIGURE_WAS             = "SET_CONFIGURE_WAS"
	LIST_CONFIGURE_WAS            = "LIST_CONFIGURE_WAS"
	REDEFINE_CLASSES              = "REDEFINE_CLASSES"
	CONFIGURE_DESC                = "CONFIGURE_DESC"
	CONFIGURE_VALUE_TYPE          = "CONFIGURE_VALUE_TYPE"
	CONFIGURE_VALUE_TYPE_DESC     = "CONFIGURE_VALUE_TYPE_DESC"
	GET_CONFIGURE_TELEGRAF        = "GET_CONFIGURE_TELEGRAF"
	SET_CONFIGURE_TELEGRAF        = "SET_CONFIGURE_TELEGRAF"
	GET_CONFIGURE_COUNTERS_SITE   = "GET_CONFIGURE_COUNTERS_SITE"
	SET_CONFIGURE_COUNTERS_SITE   = "SET_CONFIGURE_COUNTERS_SITE"

	// Alert scripting commands
	GET_ALERT_SCRIPTING_CONTETNS        = "GET_ALERT_SCRIPTING_CONTETNS"
	GET_ALERT_SCRIPTING_CONFIG_CONTETNS = "GET_ALERT_SCRIPTING_CONFIG_CONTETNS"
	SAVE_ALERT_SCRIPTING_CONTETNS       = "SAVE_ALERT_SCRIPTING_CONTETNS"
	SAVE_ALERT_SCRIPTING_CONFIG_CONTETNS = "SAVE_ALERT_SCRIPTING_CONFIG_CONTETNS"
	GET_ALERT_SCRIPT_LOAD_MESSAGE       = "GET_ALERT_SCRIPT_LOAD_MESSAGE"
	GET_ALERT_REAL_COUNTER_DESC         = "GET_ALERT_REAL_COUNTER_DESC"
	GET_PLUGIN_HELPER_DESC              = "GET_PLUGIN_HELPER_DESC"

	// XML and cluster commands
	GET_XML_COUNTER = "GET_XML_COUNTER"
	CLUSTER_TEST1   = "CLUSTER_TEST1"

	// Export commands
	EXPORT_OBJECT_TIME_COUNTER    = "EXPORT_OBJECT_TIME_COUNTER"
	EXPORT_OBJECT_REGULAR_COUNTER = "EXPORT_OBJECT_REGULAR_COUNTER"
	EXPORT_APP_SUMMARY            = "EXPORT_APP_SUMMARY"

	// Stack analyzer commands
	GET_STACK_ANALYZER = "GET_STACK_ANALYZER"
	GET_STACK_INDEX    = "GET_STACK_INDEX"
	PSTACK_ON          = "PSTACK_ON"

	// Database commands
	ACTIVE_QUERY_LIST                = "ACTIVE_QUERY_LIST"
	EXIST_QUERY_LIST                 = "EXIST_QUERY_LIST"
	LOAD_QUERY_LIST                  = "LOAD_QUERY_LIST"
	LOCK_LIST                        = "LOCK_LIST"
	DB_PROCESS_DETAIL                = "DB_PROCESS_DETAIL"
	DB_EXPLAIN_PLAN                  = "DB_EXPLAIN_PLAN"
	DB_PROCESS_LIST                  = "DB_PROCESS_LIST"
	DB_VARIABLES                     = "DB_VARIABLES"
	DB_KILL_PROCESS                  = "DB_KILL_PROCESS"
	GET_INTERVAL_SNAPSHOT_TASK       = "GET_INTERVAL_SNAPSHOT_TASK"
	CHANGE_INTERVAL_SNAPSHOT_TASK    = "CHANGE_INTERVAL_SNAPSHOT_TASK"
	SCHEMA_SIZE_STATUS               = "SCHEMA_SIZE_STATUS"
	TABLE_SIZE_STATUS                = "TABLE_SIZE_STATUS"
	INNODB_STATUS                    = "INNODB_STATUS"
	GET_QUERY_INTERVAL               = "GET_QUERY_INTERVAL"
	SET_QUERY_INTERVAL               = "SET_QUERY_INTERVAL"
	SLAVE_STATUS                     = "SLAVE_STATUS"
	EXPLAIN_PLAN_FOR_THREAD          = "EXPLAIN_PLAN_FOR_THREAD"
	USE_DATABASE                     = "USE_DATABASE"

	// Database realtime commands
	DB_REALTIME_CONNECTIONS    = "DB_REALTIME_CONNECTIONS"
	DB_REALTIME_ACTIVITY       = "DB_REALTIME_ACTIVITY"
	DB_DAILY_ACTIVITY          = "DB_DAILY_ACTIVITY"
	DB_REALTIME_RESPONSE_TIME  = "DB_REALTIME_RESPONSE_TIME"
	DB_REALTIME_HIT_RATIO      = "DB_REALTIME_HIT_RATIO"
	DB_DAILY_CONNECTIONS       = "DB_DAILY_CONNECTIONS"
	DB_DIGEST_TABLE            = "DB_DIGEST_TABLE"
	DB_MAX_TIMER_WAIT_THREAD   = "DB_MAX_TIMER_WAIT_THREAD"
	DB_LOAD_DIGEST_COUNTER     = "DB_LOAD_DIGEST_COUNTER"
	DB_LAST_DIGEST_TABLE       = "DB_LAST_DIGEST_TABLE"

	// Apache and Redis commands
	APACHE_SERVER_STATUS = "APACHE_SERVER_STATUS"
	DUMP_APACHE_STATUS   = "DUMP_APACHE_STATUS"
	REDIS_INFO           = "REDIS_INFO"
	DEBUG_SERVER         = "DEBUG_SERVER"
	DEBUG_AGENT          = "DEBUG_AGENT"
	REALTIME_SERVICE_GROUP = "REALTIME_SERVICE_GROUP"
	STATUS_AROUND_VALUE    = "STATUS_AROUND_VALUE"

	// Account management commands
	LIST_ACCOUNT           = "LIST_ACCOUNT"
	ADD_ACCOUNT            = "ADD_ACCOUNT"
	CHECK_ACCOUNT_ID       = "CHECK_ACCOUNT_ID"
	EDIT_ACCOUNT           = "EDIT_ACCOUNT"
	REMOVE_ACCOUNT         = "REMOVE_ACCOUNT"
	LIST_ACCOUNT_GROUP     = "LIST_ACCOUNT_GROUP"
	GET_GROUP_POLICY_ALL   = "GET_GROUP_POLICY_ALL"
	EDIT_GROUP_POLICY      = "EDIT_GROUP_POLICY"
	ADD_ACCOUNT_GROUP      = "ADD_ACCOUNT_GROUP"

	// Object type commands
	DEFINE_OBJECT_TYPE = "DEFINE_OBJECT_TYPE"
	EDIT_OBJECT_TYPE   = "EDIT_OBJECT_TYPE"

	// Tag counter commands
	TAGCNT_DIV_NAMES       = "TAGCNT_DIV_NAMES"
	TAGCNT_TAG_NAMES       = "TAGCNT_TAG_NAMES"
	TAGCNT_TAG_VALUES      = "TAGCNT_TAG_VALUES"
	TAGCNT_TAG_VALUE_DATA  = "TAGCNT_TAG_VALUE_DATA"
	TAGCNT_TAG_ACTUAL_DATA = "TAGCNT_TAG_ACTUAL_DATA"

	// Visitor commands
	VISITOR_REALTIME          = "VISITOR_REALTIME"
	VISITOR_REALTIME_TOTAL    = "VISITOR_REALTIME_TOTAL"
	VISITOR_REALTIME_GROUP    = "VISITOR_REALTIME_GROUP"
	VISITOR_LOADDATE          = "VISITOR_LOADDATE"
	VISITOR_LOADDATE_TOTAL    = "VISITOR_LOADDATE_TOTAL"
	VISITOR_LOADDATE_GROUP    = "VISITOR_LOADDATE_GROUP"
	VISITOR_LOADHOUR_GROUP    = "VISITOR_LOADHOUR_GROUP"

	// Summary load commands
	LOAD_SERVICE_SUMMARY        = "LOAD_SERVICE_SUMMARY"
	LOAD_SQL_SUMMARY            = "LOAD_SQL_SUMMARY"
	LOAD_APICALL_SUMMARY        = "LOAD_APICALL_SUMMARY"
	LOAD_IP_SUMMARY             = "LOAD_IP_SUMMARY"
	LOAD_UA_SUMMARY             = "LOAD_UA_SUMMARY"
	LOAD_SERVICE_ERROR_SUMMARY  = "LOAD_SERVICE_ERROR_SUMMARY"
	LOAD_ALERT_SUMMARY          = "LOAD_ALERT_SUMMARY"
	LOAD_ENDUSER_NAV_SUMMARY    = "LOAD_ENDUSER_NAV_SUMMARY"
	LOAD_ENDUSER_AJAX_SUMMARY   = "LOAD_ENDUSER_AJAX_SUMMARY"
	LOAD_ENDUSER_ERROR_SUMMARY  = "LOAD_ENDUSER_ERROR_SUMMARY"

	// Batch commands
	BATCH_HISTORY_LIST         = "BATCH_HISTORY_LIST"
	BATCH_HISTORY_DETAIL       = "BATCH_HISTORY_DETAIL"
	BATCH_HISTORY_STACK        = "BATCH_HISTORY_STACK"
	BATCH_ACTIVE_STACK         = "BATCH_ACTIVE_STACK"
	OBJECT_BATCH_ACTIVE_LIST   = "OBJECT_BATCH_ACTIVE_LIST"

	// CUBRID database commands
	CUBRID_DB_REALTIME_DML             = "CUBRID_DB_REALTIME_DML"
	CUBRID_DB_REALTIME_STATUS          = "CUBRID_DB_REALTIME_STATUS"
	CUBRID_ACTIVE_DB_LIST              = "CUBRID_ACTIVE_DB_LIST"
	CUBRID_DB_SERVER_INFO              = "CUBRID_DB_SERVER_INFO"
	CUBRID_DB_PERIOD_MULTI_DATA        = "CUBRID_DB_PERIOD_MULTI_DATA"
	CUBRID_DB_LONG_PERIOD_MULTI_DATA   = "CUBRID_DB_LONG_PERIOD_MULTI_DATA"
	CUBRID_DB_REALTIME_MULTI_DATA      = "CUBRID_DB_REALTIME_MULTI_DATA"
	CUBRID_DB_LONG_TRANSACTION_DATA    = "CUBRID_DB_LONG_TRANSACTION_DATA"
	CUBRID_GET_ALERT_CONFIGURE         = "CUBRID_GET_ALERT_CONFIGURE"
	CUBRID_SET_ALERT_CONFIGURE         = "CUBRID_SET_ALERT_CONFIGURE"
)

// Configuration result codes
const (
	APPLY_CONFIGURE_WAS_RESULT_OK      = 200
	APPLY_CONFIGURE_WAS_RESULT_RUNNING = 300
)

// FreeCmds is a set of commands that don't require authentication
var FreeCmds = map[string]bool{
	LOGIN:          true,
	SERVER_VERSION: true,
	SERVER_TIME:    true,
}
